In [1]:
import numpy as np

In [8]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [11]:
l = [[1,2,3],[4,5,6], [7,8,9]] #list is 1 dimentional
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [42]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]]) #array is 2 dimentional
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [20]:
arr3 = np.zeros(6)
arr3
arr4 = np.zeros((4,6))
arr4

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
arr5 = np.ones((3,5))
arr5

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
arr6 = np.linspace(1,10,8)
arr6

array([ 1.        ,  2.28571429,  3.57142857,  4.85714286,  6.14285714,
        7.42857143,  8.71428571, 10.        ])

In [29]:
np.random.rand(3) #values between 0-1 is normalization

array([0.17253133, 0.60711037, 0.70191038])

In [36]:
np.random.randn(10) #values between -3,3 is standardization

array([ 0.89042696,  0.54706659, -0.15479666, -0.39715174,  0.04991329,
        0.59833555,  0.10840824, -0.00442167,  0.00149446,  0.17722808])

In [38]:
np.random.randint(5,15,9)

array([ 8, 13,  6,  6, 11,  9, 13, 12, 11])

In [52]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
arr2.shape

(3, 3)

In [45]:
arr2.size

9

In [46]:
arr2.dtype

dtype('int64')

In [47]:
arr2.min()

np.int64(1)

In [48]:
arr2.max()

np.int64(9)

In [49]:
arr2.sum()

np.int64(45)

In [51]:
np.sum(arr2, axis=0) #provides the sums of colomns

array([12, 15, 18])

In [53]:
np.sum(arr2, axis=1) #provides the sums of rows

array([ 6, 15, 24])

In [55]:
arr2.mean()

np.float64(5.0)

In [56]:
arr2.std()

np.float64(2.581988897471611)

In [58]:
arr2.argmax() #provides the index of largest number

np.int64(8)

In [59]:
arr7 = np.arange(1,31)
arr7

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [60]:
arr7.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [64]:
arr7.resize(5,6)
arr7

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])