In [2]:
# Indexing and Slicing of vectors(1 D array)
# Indexing and Slicing of matrixes(2 D arrays)
# Boolean Indexing

In [3]:
import numpy as np

In [4]:
arr = np.arange(11, 21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [7]:
arr[5]

np.int64(16)

In [9]:
arr[1: 5]

array([12, 13, 14, 15])

In [10]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [15]:
arrSlice = arr[0::3]
arrSlice

array([11, 14, 17, 20])