In [1]:
# Indexing and Slicing of vectors(1 D array)
# Indexing and Slicing of matrixes(2 D arrays)
# Boolean Indexing

In [2]:
import numpy as np

In [3]:
arr = np.arange(11, 21)
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[5]

np.int64(16)

In [5]:
arr[1: 5]

array([12, 13, 14, 15])

In [6]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [7]:
arrSlice = arr[0::3]
arrSlice

array([11, 14, 17, 20])

In [9]:
arr_Slice = np.arange(1, 31).reshape(6,5)
arr_Slice

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [22]:
arr_Slice[3]

array([16, 17, 18, 19, 20])

In [23]:
arr_Slice[2,2]

np.int64(13)

In [24]:
slice = arr_Slice[0:2,1:3] #slicing of a matrix (1st rows then colomns)
slice

array([[2, 3],
       [7, 8]])

In [25]:
slice2 = arr_Slice[3:,3:]
slice2

array([[19, 20],
       [24, 25],
       [29, 30]])

In [27]:
arr_Slice[:,3]

array([ 4,  9, 14, 19, 24, 29])

In [35]:
#Boolen indexing
arr1 = np.arange(10,21)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
boolIndex = arr1 % 2 == 0
boolIndex

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [37]:
arr1 = arr1[boolIndex]
arr1

array([10, 12, 14, 16, 18, 20])