In [3]:
# Arithmetic Operations
# Broadcasting
# Deep and Shallow copy
# Matrix Operations
# Advanced Array Manipulation
# Stacking Array
# Spliting Array

In [36]:
import numpy as np

In [37]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [38]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [39]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [40]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [41]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [42]:
a1 // a2

array([0, 0, 0, 0, 0])

In [43]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [44]:
# Broadcasting

In [45]:
l = [10, 20, 30, 40]
a3 = np.array(l)

In [46]:
a3 + 10

array([20, 30, 40, 50])

In [48]:
a4 = np.arange(1,26).reshape(5,5)
a4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [49]:
a4 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [50]:
# Deep and Shallow Copy

In [52]:
a5 = np.arange(1,21)
a5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [54]:
slice = a5[:5]
slice

array([1, 2, 3, 4, 5])

In [58]:
slice = slice*10
slice

array([100, 200, 300, 400, 500])

In [59]:
a5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [63]:
# By slicing an  array it creates the shallow copy and changing in slice didn't effect the main array,
# b = a.copy() also this is shallow copy
# but by copying the complete array into another variable and made changing in that variable also effects the main array 
# (deep copy)
# b = a (deep copy)

In [64]:
# Matric Operations

In [70]:
a5 = np.array([[1,2], [3,4]])
a6 = np.array([[5,6], [7,8]])

In [73]:
a5

array([[1, 2],
       [3, 4]])

In [75]:
a6

array([[5, 6],
       [7, 8]])

In [77]:
#matrix multiplixcationa

a5 @ a6

array([[19, 22],
       [43, 50]])

In [79]:
#also multiplication can be done as

np.dot(a5,a6)

array([[19, 22],
       [43, 50]])

In [80]:
# Transpose of array
a5Copy = a5.copy()
a5Copy

array([[1, 2],
       [3, 4]])

In [87]:
a5Copy = a5Copy.T

In [88]:
a5

array([[1, 2],
       [3, 4]])

In [89]:
a5Copy

array([[1, 2],
       [3, 4]])

In [90]:
# Array Stackinga
# You cannot stack the matrix only vectors can be stacked

In [91]:
a7 = np.array([1,2,3])
a8 = np.array([4,5,6])

In [92]:
# Vertical Stack, Horizontal Stack, Simple Stack

In [93]:
np.vstack((a7,a8))

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
np.hstack((a7,a8))

array([1, 2, 3, 4, 5, 6])

In [98]:
np.column_stack((a7,a8))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [100]:
#Spliting Array

In [101]:
a9 = np.arange(16).reshape(4,4)
a9

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
np.hsplit(a9, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [105]:
a10 = np.vsplit(a9, 2)
a10

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [106]:
for i in a10:
    print(i)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
